# Generated by Django 5.0.1 on 2024-01-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_borrowedbook_isreturned_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='returning_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
