# Generated by Django 5.0.1 on 2024-01-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_borrowedbook_returning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='returning_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
