# Generated by Django 5.0.1 on 2024-01-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_alter_borrowedbook_returning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='returning_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
