# Generated by Django 5.0.1 on 2024-01-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_alter_borrowedbook_returning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='isReturned',
            field=models.BooleanField(default=False),
        ),
    ]
